"""
Defines the shared state passed between nodes in the LangGraph
financial-planning workflow.
"""

from __future__ import annotations

from decimal import Decimal
from typing import TypedDict

from schemas.profile import FinancialProfile
from schemas.transaction import TransactionBatch
from schemas.goal import FinancialGoal, GoalAnalysis
from schemas.debt import Debt, DebtAnalysis
from schemas.analysis import FinancialAnalysis
from schemas.budget import MonthlyBudget


class FinancialState(TypedDict, total=False):
    """
    Shared state for the financial-planning LangGraph.

    Each agent/node reads the information it needs from this state
    and writes its results back into the state.
    """

    # User information
    profile: FinancialProfile

    # Raw / processed financial data
    transactions: TransactionBatch

    # User's financial goals
    goals: list[FinancialGoal]

    # User's debts / loans
    debts: list[Debt]

    # Deterministic financial analysis
    financial_analysis: FinancialAnalysis

    # Budget generated by the budget calculator
    budget: MonthlyBudget

    # Detailed goal analysis
    goal_analysis: list[GoalAnalysis]

    # Detailed debt analysis
    debt_analysis: list[DebtAnalysis]

    emergency_fund: Decimal
    llm_model: str

    # Agent-generated recommendations
    recommendations: list[str]

    # Final generated report
    report: str
    report_path: str
    report_generation_seconds: float

    # Workflow information
    current_step: str

    # Error information
    errors: list[str]
